version: "3.4"

services:
  backend:
    build:
      dockerfile: api.Dockerfile
      context: .
    environment:
      - NODE_ENV=production
      - APP_PORT=8080
  frontend:
    build:
      dockerfile: client.Dockerfile
      context: .
    ports:
      - 80:80
      - 443:443
    environment:
      - NODE_ENV=production
