version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x

    commands:
      - echo Installing source NPM dependencies...
      - npm ci

  build:
    commands:
      - echo Running code quality checks...
      - npm run lint
      - npm run prettify

cache:
  paths:
    - '/**/*'
